In [1]:
list=[2345,565,48974,6464,-16541]

In [2]:
list

[2345, 565, 48974, 6464, -16541]

In [3]:
import numpy as np

In [4]:
a = np.array(list)

a

In [6]:
#array can't have diff data types

In [7]:
b = np.array([12,454,63.5,True,"abc"])

In [8]:
b

array(['12', '454', '63.5', 'True', 'abc'], dtype='<U32')

In [9]:
type(b)

numpy.ndarray

In [10]:
a.mean()

8361.4

In [11]:
b = np.array([12,454,63.5,True])

In [12]:
b

array([ 12. , 454. ,  63.5,   1. ])

In [13]:
b = np.array([12,454,63.5,"abc"])

In [14]:
b

array(['12', '454', '63.5', 'abc'], dtype='<U32')

---

In [16]:
list

[2345, 565, 48974, 6464, -16541]

In [17]:
l = list

In [18]:
l

[2345, 565, 48974, 6464, -16541]

In [19]:
l[1:]

[565, 48974, 6464, -16541]

In [20]:
l[0:2]

[2345, 565]

In [21]:
l[::2]

[2345, 48974, -16541]

In [22]:
l[::-1]

[-16541, 6464, 48974, 565, 2345]

In [23]:
a[:]

array([  2345,    565,  48974,   6464, -16541])

In [24]:
a[-1]

-16541

In [25]:
b=a[0:2]

In [26]:
b

array([2345,  565])

In [27]:
a[0]=1

In [28]:
a

array([     1,    565,  48974,   6464, -16541])

In [29]:
b

array([  1, 565])

In [30]:
b[1]= 555

In [31]:
b

array([  1, 555])

In [32]:
a

array([     1,    555,  48974,   6464, -16541])

In [33]:
c=a.copy()

In [34]:
c

array([     1,    555,  48974,   6464, -16541])

In [35]:
c[1]=-1

In [36]:
c

array([     1,     -1,  48974,   6464, -16541])

In [37]:
a

array([     1,    555,  48974,   6464, -16541])

In [38]:
l1 = [20, 'a', 21, 'b', 22, 'c', 23, 'd', 24, 'e', 25, 'f']

In [39]:
l1[1::2]

['a', 'b', 'c', 'd', 'e', 'f']

In [40]:
l1[1:12:2]

['a', 'b', 'c', 'd', 'e', 'f']

In [41]:
l1[-1:-12:-2]

['f', 'e', 'd', 'c', 'b', 'a']